### ISSUE TITLE
Are the pretrained model weights in RGB or BGR order?

### ISSUE THREAD

**Issue by vinbhaskara** [ucbdrive/dla#12]
Does the pre-trained DLA model expect input images in BGR or RGB channel order? Thanks.

**Comment by fyu** [comment]
The data was loaded with default pytorch dataloader: https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader

**Comment by vinbhaskara** [comment]
Thanks, so that means they are in RGB order.
