### ISSUE TITLE
The .project weight in '.pth' file seems mismatch with the model?

### ISSUE THREAD

**Issue by feiyuhuahuo** [ucbdrive/dla#15]
I've taken a look at the '.pth' file and I found there are two `.project.weight` when the depth of a tree is 2.
This is for dla34:
![image](https://user-images.githubusercontent.com/32631344/66973661-359cb300-f0cb-11e9-8680-1b90ffb04f34.png)
![image](https://user-images.githubusercontent.com/32631344/66973692-4d743700-f0cb-11e9-8928-190ae1668fef.png)
According to the figure in your paper and your code:
![image](https://user-images.githubusercontent.com/32631344/66973815-a47a0c00-f0cb-11e9-91c3-6a5a9d1a0239.png)

 `self.project` comes after downsample and appears only once during a single level, but why here are two `.project.weight`  in the pth?
Hope for your reply soon.

**Comment by JasonZhao001** [comment]
I haven't found any pretrained weight (.pth) file provided in this repo, could you tell me where did you downloaded it? THX!
