### ISSUE TITLE
dl.yf.io is down 

### ISSUE THREAD

**Issue by rupakl** [ucbdrive/dla#6]
The link [http://dl.yf.io/dla/models/](url) to download pretrained models seems to be down.

**Comment by zijianh4** [comment]
Hi @fyu ,
Thanks for your great work! It seems that http://dl.yf.io/dla/models is down again. Or the model zoo is transferred to somewhere else? Thanks!

**Comment by tuclen-3** [comment]
Hi @fyu,
The link [http://dl.yf.io/dla/models/](https://github.com/ucbdrive/dla/issues/url) to download pretrained models seems to be down

**Comment by Zhou-YT410** [comment]
Hi @fyu,
The link [http://dl.yf.io/dla/models/](https://github.com/ucbdrive/dla/issues/url) to download pretrained models seems to be down

**Comment by fyu** [comment]
The server is back now. However, IT is still investigating why the server is not stable recently.

**Comment by hcaltenco** [comment]
Hi, as of February 9th, 2024. It seems that the server is down again. Please check if possible to get it back

**Comment by btanagho** [comment]
Hi, Is the server down for anybody today? Is it possible to get it back up?

**Comment by Hemilibeatriz** [comment]
> Olá, o servidor está fora do ar para alguém hoje? É possível colocá-lo de volta?

Yes, since yesterday :(
